version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build:
      context: .
      dockerfile: mydockerfile  # Update this line to the new Dockerfile name
    ports:
      - "5000:5000"
    depends_on:
      - mongo

